import type { Metadata } from "next";
import "./globals.css";
import { STYLES } from "./styles";
import Navbar from "./components/Navbar";
import Cursor from "./components/Cursor";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>{STYLES}</style>
      </head>
      <body className="tanit-root">
        <Navbar/>
        <Cursor/>
        {children}
      </body>
    </html>
  );
}
